In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

/Users/sreevardhan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
tf.__version__

'2.16.1'

In [3]:
df=pd.read_csv("Churn_Modelling.csv")
X=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [8]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [11]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

Initilizing ANN

In [14]:
ann=tf.keras.models.Sequential()

Adding input layer and first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding Second Hidden Layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Output Layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

Traning The Data

In [19]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [20]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.6460 - accuracy: 0.6774
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5110 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4653 - accuracy: 0.7976
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4371 - accuracy: 0.8051
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4191 - accuracy: 0.8152
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4039 - accuracy: 0.8250
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3902 - accuracy: 0.8332
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3791 - accuracy: 0.8382
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3717 - accuracy: 0.8431
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3667 - accura

In [22]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5

1/1 [==============================] - 0s 33ms/step


array([[False]])

In [23]:
y_pred=ann.predict(X_test)
y_pred = (y_pred >0.5)

63/63 [==============================] - 0s 1ms/step


In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1512   83]
 [ 198  207]]


0.8595